### ISSUE TITLE
Is it possible to load a multiple contextmenu?

### ISSUE THREAD

**Issue by ibakayoko** [prograhammer/bootstrap-table-contextmenu#5]
Hello,

Thank you for the nice plugin. 
I have a table that displays items of different types { folders and files }.
I want to have different contextMenu for each type.

Is it possible to do that with the plugin?

**Comment by prograhammer** [comment]
Ah, ok, I had thought once that someone might need that. Let me see this weekend...

**Comment by ibakayoko** [comment]
Thank you

**Comment by prograhammer** [comment]
Hi, @ibakayoko 

See this fiddle: http://jsfiddle.net/t3a9ug81/1/
Notice in this fiddle that each button shows a different context menu. Also notice that right-clicking row 3 and right-clicking row 4 also bring up different context menus.

I added an option called `beforeContextMenuRow` that will allow you to more programmatically show the context menu. Set it to a function and in your function use the method `showContextMenu` like `$('#table').bootstrapTable('showContextMenu',{event:e, ... });` to show the context menu you want. Just make sure to return false to prevent the default context menu behavior from happening afterwards. I'll update the documentation/demo tomorrow, but refer to the fiddle above for now. Feel free to ask me any more questions for clarification.

**Comment by ibakayoko** [comment]
I will checkout the latest code and try to implement on my project.

I will report the result of my integration.

Thank you very much

**Comment by ibakayoko** [comment]
Works very well.

```
 var $table = $('#grid');

      $table.bootstrapTable({
            //contextMenu: '#folders-menu',
            beforeContextMenuRow: function(e, row, b){  
                 if(row.type == 'folders'){
                        $table.bootstrapTable('showContextMenu',{event:e, contextMenu:'#folders-menu'});
                    }
                    else if(row.type == 'files'){
                        $table.bootstrapTable('showContextMenu',{event:e, contextMenu:'#files-menu'});
                    }  

                 return false;

            },          
            onContextMenuItem: function(row, $el){
                if($el.data("item") == "edit"){
                    alert("Edit: " + row.type + ' ' + row.name + ' ' + row.modified_at);
                } else if($el.data("item") == "delete"){
                    alert("Delete: " + row.type + ' ' + row.name + ' ' + row.modified_at);
                } else if($el.data("item") == "action1"){
                    alert("Action1: " + row.type + ' ' + row.name + ' ' + row.modified_at);
                } else if($el.data("item") == "action2"){
                    alert("Action2: " + row.type + ' ' + row.name + ' ' + row.modified_at);
                }
            }
        });

```

**Comment by prograhammer** [comment]
Yeah I think that looks great. And you can have conditions in your `onContextMenuItem` like 

```
 if ($el.data("item") == "edit" && row.type == "folders")  {
      // edit folders
 }
```
