### ISSUE TITLE
Context Menu does not stay open on Firefox

### ISSUE THREAD

**Issue by ibakayoko** [prograhammer/bootstrap-table-contextmenu#6]
When you right click on the table row to open the contextMenu it closes itself immediately after the right click. Tje contextMenu does not stay open.

It works fine on Chrome.

**Comment by prograhammer** [comment]
Hi @ibakayoko 

I checked the [demo](http://www.prograhammer.com/demos/bootstrap-table-contextmenu/) and the [jsFiddle](http://jsfiddle.net/t3a9ug81/1/) and both work in Firefox. Do those work for you in Firefox?

**Comment by ibakayoko** [comment]
I have done a screen recording http://sendvid.com/mzo02oyj to allow you to see the issue on firefox.

The issue is on the demo and the jsFiidle.

**Comment by prograhammer** [comment]
Ah, checked it on mac, looks like a right-click problem on mac firefox. Looking into the problem...

**Comment by prograhammer** [comment]
Thanks for reporting this bug @ibakayoko and the excellent screen capturing! Try in this fiddle: http://jsfiddle.net/1n1gcb1x/

**Comment by prograhammer** [comment]
Thanks @ibakayoko for reporting this bug and for the great screen capturing! It's looks fixed now. You can check the demo again: [demo](http://www.prograhammer.com/demos/bootstrap-table-contextmenu/)

Also, in a few days I plan to do another update that will let you set a class that will shield areas of the contextmenu from automatically closing the menu when clicked. This is good for situations where you may want some input fields or buttons on the context menu.

**Comment by prograhammer** [comment]
Wait...found another issue with the right click on mac...fixing...

**Comment by prograhammer** [comment]
Still working on this issue...

**Comment by prograhammer** [comment]
Ok, so Mac OSX on Firefox was triggering an extra click for some reason on right-click. Mouse events and right-clicking seem to be a big ordeal, but fortunately I was able to fix it without adding any additional bloat to the code. So check the demo again and let me know. Works great on Mac OSX finally!

New fiddle:
http://jsfiddle.net/147bb2vs/

Also see demo again:
[demo](http://www.prograhammer.com/demos/bootstrap-table-contextmenu/)

**Comment by ibakayoko** [comment]
Well done. It works perfectly.
Thank you
