### ISSUE TITLE
Row index in onContextMenuItem event

### ISSUE THREAD

**Issue by Real-Gecko** [prograhammer/bootstrap-table-contextmenu#7]
Is it possible to add row index parameter to onContextMenuItem event?
I need something like this:

``` javascript
onContextMenuItem: function(row, index, $el) {
    if($el.data("item") == "update" {
        row.name = 'something';
        $table.bootstrapTable('updateRow', {
            index: index,
            row: row
        });
    }
}
```

**Comment by Real-Gecko** [comment]
I found a solution

``` javascript
beforeContextMenuRow: function(e, row) {
    var index = ($(e.currentTarget).data("index"));
    $table.bootstrapTable('showContextMenu', { event: e } )
    .off('contextmenu-item.bs.table')
    .on('contextmenu-item.bs.table', function(ev, row, $el) {
        if($el.data("item") == "update") {
            row.name = "something";
            $('#list-table').bootstrapTable('updateRow', { 'index': index, 'row': row });
        }
    });
    return false;
}
```

However I'm not sure it does not have any overheads or caveats :)

**Comment by prograhammer** [comment]
Hmmm...You could use the [updateByUniqueId](http://issues.wenzhixin.net.cn/bootstrap-table/#methods/updateByUniqueId.html) method to accomplish this. But I do see it is good to have the index available. Let me look at the best way to provide the index and I'll tag a new release this weekend. Thanks for this recommendation. :-)
