### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by fenichelar** [prograhammer/bootstrap-table-contextmenu#9]
Your latest release is broken! It has been fixed in a commit but not yet released. Bower install fails. Make a new release :)

**Comment by prograhammer** [comment]
Ah didn't realize it was breaking bower install...I'll tag a new release first thing in the morning, thanks!

**Comment by prograhammer** [comment]
Fixed, sorry for the delay! I've been transitioning to a new job :-)

**Comment by fenichelar** [comment]
No problem, just had to specify the commit in bower. But now those less familiar will not struggle. Loving the context menu! Enjoy the new job!!
